"""empty message

Revision ID: 782a43d69069
Revises: aa2e581ff74b
Create Date: 2023-12-15 13:32:58.415911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782a43d69069'
down_revision = 'aa2e581ff74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
