"""empty message

Revision ID: 85aa3dcdd238
Revises: 
Create Date: 2023-11-17 19:36:12.752619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85aa3dcdd238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movieRatings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movieRatings', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
